### ISSUE TITLE
使用编译好的merge_pdf.exe合并pdf时出错

### ISSUE THREAD

**Issue by changwh** [shylocks/51zhy_pdf#3]
```bash
PS C:\Users\xxxx\Downloads\yd-test> .\merge_pdf.exe 68260727
PdfReadWarning: Object 9 0 not defined. [pdf.py:1629]
Traceback (most recent call last):
  File "merge_pdf.py", line 32, in <module>
  File "merge_pdf.py", line 27, in file_name_walk
  File "merge_pdf.py", line 17, in pdf_cat
  File "site-packages\PyPDF2\pdf.py", line 482, in write
  File "site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
  File "site-packages\PyPDF2\pdf.py", line 1631, in getObject
PyPDF2.utils.PdfReadError: Could not find object.
[10668] Failed to execute script merge_pdf
```
在合并下载好的pdf时报错，经过实验把其中两张引起出错的pdf暂时移除之后能够正常合并。
引起错误的两张pdf可以正常单独打开，请问这是什么原因呢？该如何解决这个问题？

**Comment by shylocks** [comment]
本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)，的版本，你可以试一下

**Comment by changwh** [comment]
> 
> 
> 本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)的版本，你可以试一下

试了一下，还是老问题。。引起问题的pdf编号为2和113，不知道是不是这两个pdf在下载的时候出来问题，但是单独打开的时候是正常的

**Comment by shylocks** [comment]
> > 本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)的版本，你可以试一下
> 
> 试了一下，还是老问题。。引起问题的pdf编号为2和113，不知道是不是这两个pdf在下载的时候出了问题，但是单独打开的时候是正常的。现在网站也暂停免费阅读了，我暂时也没法重新下载了。。如果方便的话能单独把这两个pdf发给我试试吗？
> 68260727-白话强化学习与PyTorch-2.pdf
> 68260727-白话强化学习与PyTorch-113.pdf

试试用Release中发布的新版本下载指定页再合并

**Comment by changwh** [comment]
> 
> 
> > > 本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)的版本，你可以试一下
> > 
> > 
> > 试了一下，还是老问题。。引起问题的pdf编号为2和113，不知道是不是这两个pdf在下载的时候出了问题，但是单独打开的时候是正常的。现在网站也暂停免费阅读了，我暂时也没法重新下载了。。如果方便的话能单独把这两个pdf发给我试试吗？
> > 68260727-白话强化学习与PyTorch-2.pdf
> > 68260727-白话强化学习与PyTorch-113.pdf
> 
> 试试用Release中发布的新版本下载指定页再合并

```bash
PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=113
pkg/prelude/bootstrap.js:1261
      return wrapper.apply(this.exports, args);
                     ^

TypeError: undefined is not a function
    at Object.<anonymous> (D:\snapshot\51zhy\index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11
```
指定页码之后会报错
```bash
PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=2,113
所在位置 行:1 字符: 30
+ .\index-win.exe 68260727 -p=2,113
+                              ~
参数列表中缺少参量。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument
```
指定多页码也会报错

整本重新下载，似乎还是会有同样的问题。而且感觉速度比之前慢得多。。

**Comment by shylocks** [comment]
> > > > 本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)的版本，你可以试一下
> > > 
> > > 
> > > 试了一下，还是老问题。。引起问题的pdf编号为2和113，不知道是不是这两个pdf在下载的时候出了问题，但是单独打开的时候是正常的。现在网站也暂停免费阅读了，我暂时也没法重新下载了。。如果方便的话能单独把这两个pdf发给我试试吗？
> > > 68260727-白话强化学习与PyTorch-2.pdf
> > > 68260727-白话强化学习与PyTorch-113.pdf
> > 
> > 
> > 试试用Release中发布的新版本下载指定页再合并
> 
> ```shell
> PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=113
> pkg/prelude/bootstrap.js:1261
>       return wrapper.apply(this.exports, args);
>                      ^
> 
> TypeError: undefined is not a function
>     at Object.<anonymous> (D:\snapshot\51zhy\index.js)
>     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
>     at Module.load (internal/modules/cjs/loader.js:813:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:14)
>     at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
>     at internal/main/run_main_module.js:17:11
> ```
> 
> 指定页码之后会报错
> 
> ```shell
> PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=2,113
> 所在位置 行:1 字符: 30
> + .\index-win.exe 68260727 -p=2,113
> +                              ~
> 参数列表中缺少参量。
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : MissingArgument
> ```
> 
> 指定多页码也会报错
> 
> 整本重新下载，似乎还是会有同样的问题。而且感觉速度比之前慢得多。。

试试cmd，PowerShell会报错

**Comment by changwh** [comment]
> 
> 
> > > > > 本地测试这个编号合并没有问题，重新编译了一个[merge_pdf.exe](https://www.lanzous.com/i93s69a)的版本，你可以试一下
> > > > 
> > > > 
> > > > 试了一下，还是老问题。。引起问题的pdf编号为2和113，不知道是不是这两个pdf在下载的时候出了问题，但是单独打开的时候是正常的。现在网站也暂停免费阅读了，我暂时也没法重新下载了。。如果方便的话能单独把这两个pdf发给我试试吗？
> > > > 68260727-白话强化学习与PyTorch-2.pdf
> > > > 68260727-白话强化学习与PyTorch-113.pdf
> > > 
> > > 
> > > 试试用Release中发布的新版本下载指定页再合并
> > 
> > 
> > ```shell
> > PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=113
> > pkg/prelude/bootstrap.js:1261
> >       return wrapper.apply(this.exports, args);
> >                      ^
> > 
> > TypeError: undefined is not a function
> >     at Object.<anonymous> (D:\snapshot\51zhy\index.js)
> >     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
> >     at Module.load (internal/modules/cjs/loader.js:813:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:725:14)
> >     at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
> >     at internal/main/run_main_module.js:17:11
> > ```
> > 
> > 
> > 指定页码之后会报错
> > ```shell
> > PS C:\Users\xxxx\Downloads\yd-test> .\index-win.exe 68260727 -p=2,113
> > 所在位置 行:1 字符: 30
> > + .\index-win.exe 68260727 -p=2,113
> > +                              ~
> > 参数列表中缺少参量。
> >     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
> >     + FullyQualifiedErrorId : MissingArgument
> > ```
> > 
> > 
> > 指定多页码也会报错
> > 整本重新下载，似乎还是会有同样的问题。而且感觉速度比之前慢得多。。
> 
> 试试cmd，PowerShell会报错

试了cmd，指定多页码下载的不报错了，但还是不能指定单页码下载
```shell
C:\Users\xxxx\Downloads\yd-test>index-win.exe 68260727 -p=2
pkg/prelude/bootstrap.js:1261
      return wrapper.apply(this.exports, args);
                     ^

TypeError: undefined is not a function
    at Object.<anonymous> (D:\snapshot\51zhy\index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11
```

最主要的合并失败的问题还是存在:sweat_smile:
目前已经改用其他方法合并pdf
